[external]
external-host ansible_host=EXTERNAL_HOST_IP ansible_user=ubuntu

[soc]
soc-host ansible_host=SOC_HOST_IP ansible_user=ubuntu

[lan]
lan-host ansible_host=LAN_HOST_IP ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
