---
- name: Install Wazuh GPG key
  shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH \
      | gpg --no-default-keyring \
            --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg \
            --import
    chmod 644 /usr/share/keyrings/wazuh.gpg
  args:
    creates: /usr/share/keyrings/wazuh.gpg

- name: Add Wazuh apt repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] \
    https://packages.wazuh.com/4.x/apt/ stable main" \
    | tee /etc/apt/sources.list.d/wazuh.list
  args:
    creates: /etc/apt/sources.list.d/wazuh.list

- name: Install wazuh-agent package
  apt:
    name: wazuh-agent={{ wazuh_version }}-*
    state: present
    update_cache: true
  environment:
    WAZUH_MANAGER: "{{ wazuh_server_ip }}"
    WAZUH_AGENT_NAME: "{{ inventory_hostname }}"

- name: Enable and start wazuh-agent service
  systemd:
    name: wazuh-agent
    enabled: true
    state: started
    daemon_reload: true
